# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bad03707da01522fb794a0832dd0659e5974649c4edba88ddd919c3eb68f86cbb43543d291f69c06d474be3f3d054ee94780d2f1496a7aecc13a0f9f780fc87a

test:
  secret_key_base: e1f66b0bc99a22b7c0ad37f051f17cc98673ef48a022c19148cc6d22b7c90bec48182e6ce1aaf00b5f0a927fc2cebdb529b0eb0ab598676b9e3a92c6cd483826

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
